name: VIP1b
main: iBa4x\VIP\Main
version: 1.0.0
api: [2.0.0]
auther: iBa4x
website: https://github.com/iBa4x/VIP1b

commands:
   sbb:
     permission: vip1b.command.sbb
     description: set teleport player do not have vip.
   sbr:
     permission: vip1b.command.sbr
     description: set block join vip.
